### ISSUE TITLE
MY Files: Share/Unshare file

### ISSUE THREAD

**Issue by ParthivPatel-BTC** [ParthivPatel-BTC/arriva_drive#3]
Logged in participant can share/unshare specific file to his/her networks.

![selection_109](https://cloud.githubusercontent.com/assets/5477412/8304155/55ddcc3e-19c1-11e5-9329-2486761e1d3d.png)

![selection_108](https://cloud.githubusercontent.com/assets/5477412/8304158/5c24d04c-19c1-11e5-851a-1b0ae528d20a.png)

**Comment by ParthivPatel-BTC** [comment]
@PragatiDoshi-BTC - Please add your estimated time

**Comment by PragatiDoshi-BTC** [comment]
This will take 30-60 minutes.

**Comment by ParthivPatel-BTC** [comment]
Share/unshare popup - Networks slider not working properly.

![selection_108](https://cloud.githubusercontent.com/assets/5477412/8323016/57907932-1a5c-11e5-92f4-28daf1b35cad.png)

**Comment by ParthivPatel-BTC** [comment]
@PragatiDoshi-BTC  - Please add your estimated time

**Comment by PragatiDoshi-BTC** [comment]
This issue will require approximately 1 hour

**Comment by PragatiDoshi-BTC** [comment]
New issue is "Checkboxes not persisting its state after closing the popup".

The approach is as below :

While opening div, I will check whether cookie has a value, if yes , then checkbox are checked using cookie value, otherwise it will appear as it is, Then we will update cookie value .  For reference link will be as below: I have used cookies to store value in addMyPopup also.

https://gist.github.com/jameshibbard/8647138

This issue will require 2-3 hours.
